# Run this CI Workflow on merges to the `main` branch
name: Merge CI
on:
  push:
    branches:
      - main

# Security permissions
permissions:
  contents: read

jobs:
  # Create release
  release:
    runs-on: ubuntu-latest
    environment: build

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Run Semantic Release to get versioning and changelog
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
